### PR TITLE
Fix `postNotification` & API Change

### LINKED ISSUE #1055: postNotification() doesn't work on Android
**Description:**

`OneSignal.postNotification()` doesn't work on Android.

**Environment**

Version of the OneSignal React-Native SDK: `3.9.1`.
SDK added with `yarn add react-native-onesignal`.

**Steps to Reproduce Issue:**

1. Install the OneSignal SDK using npm into your project,
1. Follow the [setup](https://documentation.onesignal.com/docs/react-native-sdk-setup) and initialize OneSignal in your main component,
1. Use `postNotification()` as mentioned [here](https://documentation.onesignal.com/docs/sdk-reference#sending-notifications) (for example on press on a button),
1. `npx react-native run-android`.

**Anything else:**

There aren't any error message. When I send a notification from the OneSignal panel or from an iOS device, it works regardless of the receiver's OS.

### PR DESCRIPTION
**Pull request by rgomezp**
Motivation:

* We want to simplify the `postNotification` function and change the API to be more consistent with Cordova & other wrappers.
* The function now takes a json object string and a success and failure callback
* Update example app to have a "Post Notification" testing button

Closes #1055

### CODE REVIEW

**Review by jkasten2 — APPROVED** [review]

File: src/index.js [hunk 1]
```diff
@@ -209,13 +209,9 @@ export default class OneSignal {
 
     /* N O T I F I C A T I O N S */
 
-    static postNotification(contents, data, player_id, otherParameters) {
+    static postNotification(notificationObjectString, onSuccess=()=>{}, onFailure=()=>{}) {
```
Comment (rgomezp) [inline src/index.js:212]: @emawby , added default arguments

File: ios/RCTOneSignal/RCTOneSignalEventEmitter.m [hunk 2]
```diff
@@ -286,30 +286,18 @@ + (void)sendEventWithName:(NSString *)name withBody:(NSDictionary *)body {
...
-        // Array of player ids
-        notification[@"include_player_ids"] = player_ids;
-    }
-
-    if (other_parameters) {
-        [notification addEntriesFromDictionary:other_parameters];
+RCT_EXPORT_METHOD(postNotification:(NSString *)jsonObjectString successCallback:(RCTResponseSenderBlock)successCallback failureCallback:(RCTResponseSenderBlock)failureCallback) {
+    if (!successCallback || !failureCallback) {
+        [OneSignal onesignal_Log:ONE_S_LL_VERBOSE message:@"postNotification must contain success & failure callbacks"];
+        return;
```
Comment (rgomezp) [inline ios/RCTOneSignal/RCTOneSignalEventEmitter.m:292]: updated cc @emawby

**Review by emawby — APPROVED** [review]
