### PR TITLE
Fixed bug where sending tag value 'false' removes the tag

### LINKED ISSUE #846: OneSignal.sendTags() behaves differently on iOS and Android
**Description:**

OneSignal.sendTags() behaves differently on iOS and Android

**Environment**

Android: 

`OneSignal.sendTags({myName: 'oneSignalIsAmazeballs',  thing: false})`

iOS:

`OneSignal.sendTags({myName: 'oneSignalIsAmazeballs',  thing: false})`

on Android, the user will have thing set to false, on iOS, thing will not be set at all.

**Steps to Reproduce Issue:**

On Android:

```
OneSignal.sendTags({sumbit1: false});
OneSignal.sendTags({sumbit2: "false"});
```

User gets properties: `{sumbit1: false, sumbit2: false}`

On iOS

```
OneSignal.sendTags({sumbit1: false});
OneSignal.sendTags({sumbit2: "false"});
```

User gets properties: `{sumbit2: false}`

**Anything else:**

Workaround: Set everything to a string before saving it with OneSignal.sendTags

### PR DESCRIPTION
**Pull request by rgomezp**
Fixes #846

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -236,12 +236,22 @@ export default class OneSignal {
     static sendTag(key, value) {
         if (!checkIfInitialized()) return;
 
+        if (typeof value !== "string") {
+            value = JSON.stringify(value);
```
Comment (jkasten2) [inline index.js]: I am not sure how the bridge treats `object` today. If we stringify everything here then it could result in some large objects sending a huge object KiBs in size. Let's limit it to just `boolean` of the bug we are fixing.
