### PR TITLE
Fix React Native Null Activity

### LINKED ISSUE #516: (Android) E/onesignal: Unable to initialize the OneSignal SDK because activity is null true or oneSignalInitDonefalse
Hello!
"react-native": "0.55.3",
"react-native-onesignal": "^3.2.3",

app.js
```
componentWillMount() {
    OneSignal.init('bddacd3f-7812-4a29-b038-.................');
    OneSignal.addEventListener('received', this.onReceived);
    OneSignal.addEventListener('opened', this.onOpened);
    OneSignal.addEventListener('ids', this.onIds);
}



onReceived(notification) {
        console.log("Notification received: ", notification);
    }

    onOpened(openResult) {
      console.log('Message: ', openResult.notification.payload.body);
      console.log('Data: ', openResult.notification.payload.additionalData);
      console.log('isActive: ', openResult.notification.isAppInFocus);
      console.log('openResult: ', openResult);
    }



    onIds(device) {
		console.log('Device info: ', device);
   }
```
1. work on iOS

2. not work on Android

### PR DESCRIPTION
**Pull request by Nightsd01**
• In some cases, especially with projects using the react-native-navigation dependency, the initial Activity would be null, preventing the SDK from initializing.
• Added a check that will launch a re-attempt timer if this occurs.
• Updated build.gradle to use a newer version (26.0.2)
• Fixes #516, #547

### CODE REVIEW

File: android/src/main/java/com/geektime/rnonesignalandroid/RNOneSignal.java [hunk 1]
```diff
@@ -107,8 +106,23 @@ private JSONObject jsonFromErrorMessageString(String errorMessage) throws JSONEx
    @ReactMethod 
    public void init(String appId) {
       Activity activity = getCurrentActivity();
-      if (activity == null || oneSignalInitDone) {
-         Log.e("onesignal", "Unable to initialize the OneSignal SDK because activity is null " + (activity == null) + " or oneSignalInitDone" + oneSignalInitDone);
+      
+      if (activity == null) {
```
Comment (jkasten2) [inline android/src/main/java/com/geektime/rnonesignalandroid/RNOneSignal.java]: Not sure what values are on `mReactApplicationContext` but can we get an Android `Context` from this if `getCurrentActivity()` gives us `null`?

**Review by jkasten2 — CHANGES_REQUESTED** [review]

File: android/src/main/java/com/geektime/rnonesignalandroid/RNOneSignal.java (hunk 1 above)
Comment (Nightsd01) [reply android/src/main/java/com/geektime/rnonesignalandroid/RNOneSignal.java]: @jkasten2 `getCurrentActivity()` is what is now used in RN to get the current activity. The old way of getting the activity (from the ReactApplicationContext object) is deprecated

https://github.com/facebook/react-native/releases/tag/v0.29.0

Comment (jkasten2) [reply android/src/main/java/com/geektime/rnonesignalandroid/RNOneSignal.java]: I believe `mReactApplicationContext.getApplicationContext()` should always be non-null.

Comment (Nightsd01) [reply android/src/main/java/com/geektime/rnonesignalandroid/RNOneSignal.java]: @jkasten2 `mReactApplicationContext.getApplicationContext()` behaves the same way. 

It seems that as of 2016, React-Native no longer guarantees this method will return a non null activity at the start of the app. So I think I'll just change it to get the activity from `mReactApplicationContext` and still check for null, and if it's null, re-check in 50ms. It appears this resolves a pretty common issue in RN applications.

**Review by jkasten2 — APPROVED** [review]

**Comment by avishayil** [comment]
Actually I still encounter this. Not seeing my device on the users list and when using function to get the player id it returns `null`.

**Comment by rgomezp** [comment]
@avishayil 
So this was never resolved? Came up recently in #797
