### PR TITLE
Fix build error related to outcome event callback

### LINKED ISSUE #1003: Unable to build in Android: unreported exception JSONException
**Description:**
Unable to build android app:

/Users/fabio/Documents/Progetti/iOS/country-italia-app/node_modules/react-native-onesignal/android/src/main/java/com/geektime/rnonesignalandroid/RNOneSignal.java:489: error: unreported exception JSONException; must be caught or declared to be thrown
               callback.invoke(RNUtils.jsonToWritableMap(outcomeEvent.toJSONObject()));
                                                                                  ^
/Users/fabio/Documents/Progetti/iOS/country-italia-app/node_modules/react-native-onesignal/android/src/main/java/com/geektime/rnonesignalandroid/RNOneSignal.java:502: error: unreported exception JSONException; must be caught or declared to be thrown
               callback.invoke(RNUtils.jsonToWritableMap(outcomeEvent.toJSONObject()));
                                                                                  ^
/Users/fabio/Documents/Progetti/iOS/country-italia-app/node_modules/react-native-onesignal/android/src/main/java/com/geektime/rnonesignalandroid/RNOneSignal.java:515: error: unreported exception JSONException; must be caught or declared to be thrown

**Environment**
React Native: 0.62.2

buildToolsVersion = "28.0.3"
minSdkVersion = 21
compileSdkVersion = 29
targetSdkVersion = 29

react-native-onesignal: 3.8.0

**Steps to Reproduce Issue:**
Try to build

### PR DESCRIPTION
**Pull request by mikechoch**
* `OutcomeEvent.java` class in native SDK has a `toJSONObject` method
  * The `toJSONObject` used to have  try-catch built into it, but this was removed so that the native controllers could take responsibility for error logging
  * Adding try-catch to the wrapper bridge now so that the error logging is handle from the wrapper bridge

Fixes #1003

### CODE REVIEW

**Review by Jeasmine — APPROVED** [review]

File: android/src/main/java/com/geektime/rnonesignalandroid/RNOneSignal.java [hunk 1]
```diff
@@ -479,40 +479,58 @@ public void inAppMessageClicked(OSInAppMessageAction result) {
...
             if (outcomeEvent == null)
                callback.invoke(new WritableNativeMap());
-            else
-               callback.invoke(RNUtils.jsonToWritableMap(outcomeEvent.toJSONObject()));
+            else {
+               try {
+                  callback.invoke(RNUtils.jsonToWritableMap(outcomeEvent.toJSONObject()));
+               } catch (JSONException e) {
+                  Log.e("OneSignal", "sendOutcomeWithValue with name: " + name + " and value: " + value + ", failed with message: " + e.getMessage());
+                  e.printStackTrace();
```
Comment (Jeasmine) [inline android/src/main/java/com/geektime/rnonesignalandroid/RNOneSignal.java]: do we need e.printStackTrace();?

Comment (mikechoch) [reply android/src/main/java/com/geektime/rnonesignalandroid/RNOneSignal.java]: Guess not since we are logging an error now and printing the message! Removing now!
