### PR TITLE
`getDeviceState` is null fix

### LINKED ISSUE #1159: [CRASH][ANDROID] NullPointerException in getDeviceState
**Description:**
We're receiving a number of crash reports originating in `RNOneSignal.getDeviceState`, stack trace attached below.

It affects every android SDK version and manufacturer.

**Environment**
`"react-native-onesignal": "^4.0.2",`
`    react: 17.0.1 => 17.0.1 
    react-native: 0.64.0-rc.2 => 0.64.0-rc.2 `

**Steps to Reproduce Issue:**
Haven't been able to reproduce the issue, it's reported on Google Play's crash dashboard.

**Anything else:**

```java
  at com.geektime.rnonesignalandroid.RNOneSignal.getDeviceState (RNOneSignal.java:4)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.facebook.react.bridge.JavaMethodWrapper.invoke (JavaMethodWrapper.java:147)
  at com.facebook.react.bridge.JavaModuleWrapper.invoke (JavaModuleWrapper.java:21)
  at com.facebook.react.bridge.queue.NativeRunnable.run (NativeRunnable.java)
  at android.os.Handler.handleCallback (Handler.java:883)
  at android.os.Handler.dispatchMessage (Handler.java:100)
  at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage (MessageQueueThreadHandler.java)
  at android.os.Looper.loop (Looper.java:237)
  at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run (MessageQueueThreadImpl.java:37)
  at java.lang.Thread.run (Thread.java:919)
```

### PR DESCRIPTION
**Pull request by rgomezp**
Fixes #1159 

ReactNative sometimes appears to run the user's code such as `getDeviceState` prior to calling `initWithContext` which is done automatically for the user. Reports indicate this happens while the app is in background.

This PR adds a check to reject the promise in the case that the state returns null.

Relevant native code: https://github.com/OneSignal/OneSignal-Android-SDK/blob/31a4d1d7894f55d361d4d94b881149bfbb8f7efe/OneSignalSDK/onesignal/src/main/java/com/onesignal/OneSignal.java#L611

## 
This change is [Reviewable](https://reviewable.io/reviews/onesignal/react-native-onesignal/1193)

### CODE REVIEW

File: android/src/main/java/com/geektime/rnonesignalandroid/RNOneSignal.java [hunk 1]
```diff
@@ -236,6 +236,10 @@ public void addEmailSubscriptionObserver() {
    @ReactMethod
    public void getDeviceState(Promise promise) {
       OSDeviceState state = OneSignal.getDeviceState();
+      if (state == null) {
+         promise.reject("Null OSDeviceState", "OSDeviceState is null");
```
Comment (jkasten2) [inline android/src/main/java/com/geektime/rnonesignalandroid/RNOneSignal.java:241]: Add a to the Android error log. Believe the Android syntax `Log.e`.

**Review by jkasten2 — CHANGES_REQUESTED** [review]

**Review by jkasten2 — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/onesignal/react-native-onesignal/1193)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @rgomezp)
